import type { Metadata } from "next";
import { Inter, Smooch_Sans } from 'next/font/google';
import "./globals.css";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-body', // Mapeia para a variável CSS --font-body
});

const smooch_sans = Smooch_Sans({
  subsets: ['latin'],
  variable: '--font-heading', // Mapeia para a variável CSS --font-heading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable} ${smooch_sans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
